version: '3.8'

services:
  # Основное Java приложение с JMX агентом
  performance-app:
    build: .
    ports:
      - "8080:8080"  # Application port
      - "9404:9404"  # JMX metrics port
    environment:
      - JAVA_OPTS=-javaagent:/app/jmx_prometheus_javaagent.jar=9404:/app/jmx-config.yaml
                   -Xms512m
                   -Xmx1g
                   -XX:+UseG1GC
    volumes:
      - ./logs:/app/logs
      - ./jmx-config.yaml:/app/jmx-config.yaml:ro
    networks:
      - monitoring

  # Prometheus для сбора метрик
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  # Grafana для визуализации
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge