# Prometheus configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Java Application with JMX metrics
  - job_name: 'jvm-metrics'
    static_configs:
      - targets: ['performance-app:9404']
    scrape_interval: 10s
    metrics_path: /metrics